### ISSUE TITLE
Do we actually need an Aptfile for libglib2.0?

### ISSUE THREAD

**Issue by swrobel** [Newlywords/heroku-buildpack-vips#40]
The README specifies that we need to use apt to install these packages:
* libglib2.0-0
* libglib2.0-dev

However Heroku says that [both of these are available by default](https://devcenter.heroku.com/articles/stack-packages#libglib2.0-0) and I have been running this buildpack for some time without installing them via Aptfile. I previously was only installing `libpoppler-glib8` via Aptfile, and recently removed the apt buildpack altogether since that dependency isn't required, and all seems to be working well on my end.

**Comment by brandoncc** [comment]
I was recently wondering this myself, but haven't had time to dig into it. I wonder if these libraries were added since the creation of the buildpack? In any case, it does seem likely that we no longer need them.

I'll leave this issue open until I have some time to experiment and make sure I can't find any issues with removing the Aptfile.

**Comment by brandoncc** [comment]
You are right, we do not need them. The buildpack has switched back to poppler, but libpoppler-glib8 is also available by default. I have updated the readme to reflect that in most cases Aptfile is not needed anymore. Thanks for pointing this out.
